spring:
  application:
    name: eureka-server

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 30000
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file: ${spring.application.name}.log

#eureka.server.enable-self-preservation=false
